#!/usr/bin/env python3

import sys

if len(sys.argv) > 1:
    f = open(sys.argv[1])
else:
    f = sys.stdin
    
total = 0   
for i in f:
    if i.startswith("@"):
        continue
    cut = i.strip("\r\n").split("\t")
    if cut[2] == "2L" and int(cut[3]) >= 10000 and int(cut[3]) <= 20000:
        total += 1
        
print(total)