#!/usr/bin/env python3

import sys

# need to use < filename to run (used fly.txt)
for i, line in enumerate(sys.stdin):
    if "_DROME" in line:
        field = line.strip("\r\n").split()
        if field[-1].startswith("FBgn"):
            print(field[3], field[2])